root: /
admin_dir: administrator/
tpl: /html/user_data/packages/default/
admin_tpl: /html/user_data/packages/admin/
image_path: /html/upload/save_image/
root_dir: /home/mioshop/mioofficial.jp/public_html
root_urlpath: null
template_code: mioshop
admin_route: administrator
user_data_route: user_data
public_path: /html
public_path_realdir: /home/mioshop/mioofficial.jp/public_html/html
image_save_realdir: /home/mioshop/mioofficial.jp/public_html/html/upload/save_image
image_temp_realdir: /home/mioshop/mioofficial.jp/public_html/html/upload/temp_image
user_data_realdir: /home/mioshop/mioofficial.jp/public_html/html/user_data
block_default_realdir: /home/mioshop/mioofficial.jp/public_html/src/Eccube/Resource/template/default/Block
block_realdir: /home/mioshop/mioofficial.jp/public_html/app/template/mioshop/Block
template_default_realdir: /home/mioshop/mioofficial.jp/public_html/src/Eccube/Resource/template/default
template_default_html_realdir: /home/mioshop/mioofficial.jp/public_html/html/template/default
template_admin_realdir: /home/mioshop/mioofficial.jp/public_html/src/Eccube/Resource/template/admin
template_admin_html_realdir: /home/mioshop/mioofficial.jp/public_html/html/template/admin
template_realdir: /home/mioshop/mioofficial.jp/public_html/app/template/mioshop
template_html_realdir: /home/mioshop/mioofficial.jp/public_html/html/template/mioshop
template_temp_realdir: /home/mioshop/mioofficial.jp/public_html/app/cache/eccube/template
csv_temp_realdir: /home/mioshop/mioofficial.jp/public_html/app/cache/eccube/csv
plugin_realdir: /home/mioshop/mioofficial.jp/public_html/app/Plugin
plugin_temp_realdir: /home/mioshop/mioofficial.jp/public_html/app/cache/plugin
plugin_html_realdir: /home/mioshop/mioofficial.jp/public_html/html/plugin
admin_urlpath: /html/template/admin
front_urlpath: /html/template/mioshop
image_save_urlpath: /html/upload/save_image
image_temp_urlpath: /html/upload/temp_image
user_data_urlpath: /html/user_data
plugin_urlpath: /html/plugin
