<?php

namespace Plugin\GmoEpsilon\Repository\Extension;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderExtensionRepository extends EntityRepository
{
    /** @var array */
    public $config;

    public function setConfig(array $config)
    {
        $this->config = $config;
    }


    /**
     * Get the orders, filtered by regular_order_id
     *
     * @param integer $regular_order_id
     * @return array()
     */
    public function getOrderByRegularOrderId($regular_order_id)
    {

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('o')
            ->from('\Eccube\Entity\Order', 'o')
            ->innerJoin('\Plugin\GmoEpsilon\Entity\Extension\OrderExtension', 'g', 'WITH', 'o.id = g.id')
            ->andWhere('g.regular_order_id = :regular_order_id')
            ->setParameter('regular_order_id', $regular_order_id)
            ->orderBy('o.create_date', 'ASC');

        return $qb
            ->getQuery()
            ->getResult();
    }

    /**
     * Check the order, matched order_id, trans_code
     *
     * @param array $params
     * @return bool
     */
    public function checkNotice($params) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('o')
            ->from('\Eccube\Entity\Order', 'o')
            ->innerJoin('\Plugin\GmoEpsilon\Entity\Extension\OrderExtension', 'g', 'WITH', 'o.id = g.id')
            ->andWhere('g.trans_code = :trans_code')
            ->setParameter('trans_code', $params['trans_code'])
            ->andWhere('o.id = :order_id')
            ->setParameter('order_id', $params['order_number']);

        $Order = $qb
            ->getQuery()
            ->getResult();

        if (empty($Order)) {
            return false;
        } else {
            return true;
        }
    }

}
